//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S7Patcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("S7Patcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    &lt;TitleSystem&gt;
        ///    &lt;BlockVersion name=&quot;TitleSystem&quot; version=&quot;1&quot;/&gt;
        ///    &lt;ChoosenBranch&gt;28&lt;/ChoosenBranch&gt;
        ///    &lt;Titles&gt;
        ///     &lt;Title&gt;
        ///      &lt;BlockVersion name=&quot;Title&quot; version=&quot;1&quot;/&gt;
        ///      &lt;TitleId&gt;28&lt;/TitleId&gt;
        ///      &lt;TitleProgression&gt;
        ///       &lt;BlockVersion name=&quot;TitleProgression&quot; version=&quot;1&quot;/&gt;
        ///       &lt;CurrentRank&gt;0&lt;/CurrentRank&gt;
        ///       &lt;CurrentTitleValue&gt;0.&lt;/CurrentTitleValue&gt;
        ///       &lt;NextRankAt&gt;2000000000.&lt;/NextRankAt&gt;
        ///      &lt;/TitleProgression&gt;
        ///     &lt;/Title&gt;
        ///    &lt;/Titles&gt;
        ///   &lt;/TitleSystem&gt;.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
